### ISSUE TITLE
More build problems on JDK 10

### ISSUE THREAD

**Issue by ehoogerbeets** [box/mojito#271]
I'm trying to do "mvn package" with the latest in master, and I'm getting these errors from the spring framework stuff:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authenticatedRestTemplateTest': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: com.box.l10n.mojito.rest.resttemplate.AuthenticatedRestTemplate com.box.l10n.mojito.rest.resttemplate.AuthenticatedRestTemplateTest.authenticatedRestTemplate; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authenticatedRestTemplate': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: com.box.l10n.mojito.rest.resttemplate.ResttemplateConfig com.box.l10n.mojito.rest.resttemplate.AuthenticatedRestTemplate.resttemplateConfig; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'resttemplateConfig' defined in file [/Users/ehoogerbeets/src/mojito/restclient/target/classes/com/box/l10n/mojito/rest/resttemplate/ResttemplateConfig.class]: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) ~[spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839) ~[spring-context-4.2.6.RELEASE.jar:4.2.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) ~[spring-context-4.2.6.RELEASE.jar:4.2.6.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766) ~[spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
        at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361) ~[spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]

```

Any ideas? I just cloned and did "mvn package" ... is there something else I should do instead?

**Comment by ehoogerbeets** [comment]
Actually, I have JDK 10. I just installed and tried JDK 1.8 and it got all the way through.

**Comment by aurambaj** [comment]
yes, java 7 or 8 is required. I've added that in the getting started doc but it is not very obvious, I'm gonna look if it can be specified in maven

**Comment by aurambaj** [comment]
Couldn't find a quick solution and I don't want to spend to much time on that. 

For the record,
> Spring Boot 2.x will no longer support Java 7 and below, being Java 8 the minimum requirement.
> 
> It’s also the first version to support Java 9. There are no plans to support Java 9 on the 1.x branch. > > This means if you want to use the latest Java release and take advantage of this framework, Spring > > Boot 2.x is your only option.

Given that, we should probably stay on java 7/8 for some time. Ideally I'd drop Java 7 to benefit from the new feature in 8 but I suppose you (@jeeyi) are still using 7. Not super urgent but it could be nice.
