### ISSUE TITLE
Zombie task detected: Maximum execution time exceeded

### ISSUE THREAD

**Issue by dragosv** [box/mojito#285]
Every time I push on an Ubuntu box I get. This happens with client 0.83

```
ERROR 20616 [main] --- c.b.l.mojito.cli.command.L10nJCommander  : Exit with error for command: push

com.box.l10n.mojito.cli.command.CommandException: Zombie task detected: Maximum execution time exceeded.
	at com.box.l10n.mojito.cli.command.CommandHelper.waitForPollableTask(CommandHelper.java:228)
	at com.box.l10n.mojito.cli.command.PushCommand.execute(PushCommand.java:115)
	at com.box.l10n.mojito.cli.command.Command.run(Command.java:37)
	at com.box.l10n.mojito.cli.command.L10nJCommander.run(L10nJCommander.java:130)
	at com.box.l10n.mojito.cli.App.run(App.java:38)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:806)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:790)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:777)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at com.box.l10n.mojito.cli.App.main(App.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by aurambaj** [comment]
There is 1h timeout on the push operation. If it exceeds the timeout the PollableTask linked to the push is marked as a zombie (though it could still be running) and so on the client side it is considered as an error.

For how long has the "push" has been running? How big is the file?

**Comment by dragosv** [comment]
It times out after just a few files and just a few minutes in total of run time.

**Comment by aurambaj** [comment]
Might be a server timezone issue? Can you check if the server is UTC? If not can you try using UTC?

**Comment by dragosv** [comment]
Yes, it was a time zone issue.
