### ISSUE TITLE
push fails

### ISSUE THREAD

**Issue by jeeyi** [box/mojito#372]
I thought branch was optional :(

I just created a repo for testing and tried to push my local file to that repo and got this error.

Stack trace:

2018-12-06 15:10:30.941  INFO 88752 [main] --- com.box.l10n.mojito.cli.application      : Unexpected error, see logs for more information
2018-12-06 15:10:30.943 ERROR 88752 [main] --- c.b.l.mojito.cli.command.L10nJCommander  : Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 0
	at java.util.Arrays$ArrayList.get(Arrays.java:3841)
	at com.box.l10n.mojito.rest.client.RepositoryClient.getBranch(RepositoryClient.java:219)
	at com.box.l10n.mojito.cli.command.PushCommand.execute(PushCommand.java:126)
	at com.box.l10n.mojito.cli.command.Command.run(Command.java:43)
	at com.box.l10n.mojito.cli.command.L10nJCommander.run(L10nJCommander.java:132)
	at com.box.l10n.mojito.cli.App.run(App.java:38)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:806)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:790)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:777)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at com.box.l10n.mojito.cli.App.main(App.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
	at java.lang.Thread.run(Thread.java:748)

**Comment by aurambaj** [comment]
@jeeyi  could it be that asset content wasn't change and it didn't re-do the extraction?
