### ISSUE TITLE
Please support more current JAVA RTEs (11 and higher)

### ISSUE THREAD

**Issue by ichaus-we** [box/mojito#575]
Hi,

thanks for your work on Mojito! I am currently evaluating it for internationalizing a JAVA desktop application.

I ran into trouble trying to use a JAVA 12 RTE.
```
...
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationException
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:178)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 83 more

```
According to Oracle javax.xml.bind was deprecated in JAVA 9 and finally removed in JAVA11
[https://docs.oracle.com/javase/10/docs/api/java.xml.bind-summary.html#packages.summary](https://docs.oracle.com/javase/10/docs/api/java.xml.bind-summary.html#packages.summary
)

Do you have any plans to support JAVA 11+ ?

Greetings from Germany
Markus

**Comment by ichaus-we** [comment]
This SO answer gives some recommendations:
[https://stackoverflow.com/questions/48204141/replacements-for-deprecated-jpms-modules-with-java-ee-apis/48204154#48204154]()

**Comment by aurambaj** [comment]
At the moment, Mojito relies on spring boot 1.3 and that only works with Java 8. I've started to work on migrating to spring 2.x which supports newer Java version but no ETA on when this will be available.

Short term the best solution is to use docker or have different JVM installed using tools like `jenv` or `sdkman`

**Comment by aurambaj** [comment]
Since this was open, we now support Spring boot 2.x on the master. Added some image to try out Java 11 as build/runtime in https://github.com/box/mojito/commit/fc9501edbcd8d47573eab165543e6087b5808a9c and very basic testing seems to show it is working fine. To be tested more.
