### ISSUE TITLE
NPE when using --fully-translated

### ISSUE THREAD

**Issue by marksteele** [box/mojito#659]
```
mojito pull -r translation-demo -sl en-US -t locale/ --fully-translated

Pull localized asset from repository: translation-demo

Localizing: messages.pot

Unexpected error: null
java.lang.NullPointerException
	at com.box.l10n.mojito.cli.command.PullCommand.shouldGenerateLocalizedFile(PullCommand.java:360)
	at com.box.l10n.mojito.cli.command.PullCommand.generateLocalizedFile(PullCommand.java:194)
	at com.box.l10n.mojito.cli.command.PullCommand.generateLocalizedFilesWithoutLocaleMapping(PullCommand.java:168)
	at com.box.l10n.mojito.cli.command.PullCommand.execute(PullCommand.java:147)
	at com.box.l10n.mojito.cli.command.Command.run(Command.java:43)
	at com.box.l10n.mojito.cli.command.L10nJCommander.run(L10nJCommander.java:138)
	at com.box.l10n.mojito.cli.App.run(App.java:41)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	at com.box.l10n.mojito.cli.App.main(App.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```

Works fine without the --fully-translated flag

**Comment by aurambaj** [comment]
I have a suspicion but would you mind sharing the output of `mojito repo-view -n translation-demo`?

**Comment by marksteele** [comment]
```
mojito repo-view -n translation-demo
View repository: translation-demo

Repository id --> 1

Repository locales --> "(en-AU)" "(en-GB)" es-ES "(fr-CA)->fr-FR" fr-FR 
```
